### ISSUE TITLE
[FEATURE] Connect to ONET API

### ISSUE THREAD

**Issue by ruchikab02** [ApoorvaAditya/illinois-app#5]
**Is your feature request related to a problem? Please describe.**
Currently, we only have mock data which is not usable for the actual app, so we need to connect to the actual onet api to get the correct data. 

**Describe the solution you'd like**
We need to establish a connection with the onet api to get the data and then we can display it.

**Comment by ApoorvaAditya** [comment]
Using the backend instead to connect to the ONET APIs / storing the ONET data.
