### ISSUE TITLE
[FEATURE] Create a backend to store onet user data

### ISSUE THREAD

**Issue by ruchikab02** [ApoorvaAditya/illinois-app#6]
**Is your feature request related to a problem? Please describe.**
We want to be able to store the onet data that is relevant to the user so that we don't have to keep recalculating the bessi results every time the app is loaded up. 

**Describe the solution you'd like**
We should save user data in mongodb that can be updated using a go program every time bessi results are changed.

**Comment by ApoorvaAditya** [comment]
Being worked on in this repo: [https://github.com/ApoorvaAditya/skills-to-jobs-building-block](https://github.com/ApoorvaAditya/skills-to-jobs-building-block).
